#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc


ReadUrlParam
NO_RESET=${URLParam[noreset]}

if [ -e "$CNF_DATADIR/Run/ears.disabled" ]; then
   DATA='{"return":"1","msg":"Unable to perform action, ears disabled."}'
   SendResponse "$DATA"
   exit 0
fi

if [ "$NO_RESET" != "1" ]; then
  EarsReset
fi

L=$[($RANDOM % ($[15 - 1] + 1))]
R=$[($RANDOM % ($[15 - 1] + 1))]
EarsMove $L $R 100

DATA='{"left":"'$L'","right":"'$R'","return":"0"}'

SendResponse "$DATA"
