#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc


if [ ! -e "$CNF_DATADIR/Run/eedomus.user" ]; then
  EEDOMUS_USER=""
else
 EEDOMUS_USER=$(cat $CNF_DATADIR/Run/eedomus.user)
fi

if [ ! -e "$CNF_DATADIR/Run/eedomus.pass" ]; then
  EEDOMUS_PASS=""
else
 EEDOMUS_PASS=$(cat $CNF_DATADIR/Run/eedomus.pass)
fi

if [ ! -e "$CNF_DATADIR/Run/eedomus.ip" ]; then
  EEDOMUS_IP=""
else
 EEDOMUS_IP=$(cat $CNF_DATADIR/Run/eedomus.ip)
fi


L0='{'
L1='"user":"'$EEDOMUS_USER'"'
L2=',"pass":"'$EEDOMUS_PASS'"'
L3=',"ip":"'$EEDOMUS_IP'"'
L4=',"return":"0"'
L10='}'
DATA=$L0$L1$L2$L3$L4$L10

SendResponse "$DATA"
