#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

mount | grep usbkey >>/dev/null 2>>/dev/nul
if [ $? -eq 0 ]; then
   UFSP=`df /mnt/usbkey| awk '{ print $5 }' | tail -n 1 2>>/dev/nul`
   
   UFSP="${UFSP%?}"
else
   UFSP=-1
fi
KFSP=`df /usr | awk '{ print $5 }' | tail -n 1 2>>/dev/nul`
KFSP="${KFSP%?}"

L0='{'
L6='"karotz_percent_used_space":"'$KFSP'"'
L7=',"usb_percent_used_space":"'$UFSP'"'
L10='}'
DATA=$L0$L6$L7$L10

SendResponse "$DATA"
