#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/utils.inc

printf -v UTEMP '%s/apps.json' $CNF_BASE_URL
Log "[UPDATE][PATCH]"  "Downloading Update List $UTEMP"
rm /tmp/patch.json >>/dev/null 2>>/dev/null
curl --connect-timeout 30 -s -L -k -o /tmp/patch.json $UTEMP

  if [ ! -e "/tmp/patch.json" ]; then
    Log "[UPDATE][PATCH]"  "Unable read Update List" 1
    DATA='"{return":"0","msg":"Unable to read update list"}'
  else
    DATA=$(cat /tmp/patch.json) 
  fi

SendResponse "$DATA"
