#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/leds.inc
source /usr/www/cgi-bin/utils.inc

printf -v UTEMP '%s/Firmware' $CNF_ROOT_URL
Log "[UPDATE][FIRMWARE]"  "Downloading Firmware List $UTEMP"
rm /tmp/firmware.json >>/dev/null 2>>/dev/null
curl --connect-timeout 30 -s -L -k -o /tmp/firmware.json $UTEMP

  if [ ! -e "/tmp/firmware.json" ]; then
    Log "[UPDATE][FIRMWARE]"  "Unable read Patch List" 1
    DATA='{"return":"0","msg":"Unable to read firmware list"}'
  else
    DATA=$(cat /tmp/firmware.json) 
  fi

SendResponse "$DATA"
