#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

VERSION=$CNF_VERSION

if [ ! -e "/karotz/etc/ok_rootfs_version" ]; then
  RVERSION="Unknown"
else
  RVERSION=$(cat /karotz/etc/ok_rootfs_version)
fi

if [ ! -e "/www/ok_patch" ]; then
  PVERSION="N/A"
else
  PVERSION=$(cat /www/ok_patch)
fi


VL='{ "version":"'$VERSION'","rootfs_version":"'$RVERSION'","patch_version":"'$PVERSION'","return":"0" }'

SendResponse "$VL"

