#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory  "$CNF_DATADIR/Moods"
CheckMandatoryDirectory  "$CNF_DATADIR/Moods/fr"
 
 
if [ -e "$CNF_DATADIR/Moods/fr/moods.lst"  ]; then
  nbline=$(cat "$CNF_DATADIR/Moods/fr/moods.lst" | wc -l )
  # TODO Check if nbline  greater than 0
  TG='{ "moods":['
  while read line;
  do
    if [ ! "$line" == "" ]; then
      saveIFS=$IFS
      IFS=':'
      set $line
      IFS=$saveIFS
      TG=$TG'{ "id":"'$1'","text":"'$2'"},'
    fi
   done < "$CNF_DATADIR/Moods/fr/moods.lst"
   TG=${TG%?}'],"return":"0"}'
else
   TG='{"return":"1","msg":"Unable to found mood list" }'
fi                     
SendResponse "$TG"
