#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory  "$CNF_DATADIR/Moods"
CheckMandatoryDirectory  "$CNF_DATADIR/Moods/fr"
 
 
if [ -e "$CNF_DATADIR/Moods/fr/moods.json"  ]; then
   TG=$(cat $CNF_DATADIR/Moods/fr/moods.json)
else
   TG='{"return":"1","msg":"Unable to found mood list" }'
fi                     
SendResponse "$TG"
