#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory  "$CNF_DATADIR/Moods"
CheckMandatoryDirectory  "$CNF_DATADIR/Moods/fr"
 
 
if [ -e "$CNF_DATADIR/Apps/Streams/radios.json"  ]; then
   TG=`cat $CNF_DATADIR/Apps/Streams/radios.json`
else
   TG='{"return":"1","msg":"Unable to found radios list" }'
fi                     
SendResponse "$TG"
