#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

ReadUrlParam

TAG_ID=${URLParam[tag]}
ZIBASE_IP=${URLParam[ip]}
CMD_ID=${URLParam[cmd]}

CheckMandatoryParameter "$ZIBASE_IP" ip
CheckMandatoryParameter "$CMD_ID" cmd

   rm -f /tmp/curlout >>/dev/null 2>>/dev/null
   URL=$(BuildZibaseUrl $ZIBASE_IP $CMD_ID 1)
   ERR=$(GetUrl "$URL")
   if [ "$ERR" -eq "0" ]; then
     if [ -e "/tmp/curlout" ]; then
       VAL=`cat /tmp/curlout | sed 's/"/\\\\"/g'`
     else
       VAL="No output received from command"
     fi
     DATA='{"return":"0","msg":"'$VAL'"}'
   else
     DATA='{"return":"1","msg":"'$(GetCurlError $ERR)'"}'$URL
   fi

   
SendResponse "$DATA"

