#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc

KillProcess
ReadUrlParam


TAG_ID=${URLParam[tag]}
EEDOMUS_IP=${URLParam[ip]}
EEDOMUS_USER=${URLParam[api_user]}
EEDOMUS_PASS=${URLParam[api_password]}
MACRO_ID=${URLParam[macro]}
PORTAL=${URLParam[portal]}

CheckMandatoryParameter "$EEDOMUS_IP" ip
CheckMandatoryParameter "$MACRO_ID" macro
CheckMandatoryParameter "$EEDOMUS_USER" api_user
CheckMandatoryParameter "$EEDOMUS_PASS" api_password
CheckMandatoryParameter "$MACRO_ID" macro
CheckMandatoryParameter "$PORTAL" portal


   rm -f /tmp/curlout >>/dev/null 2>>/dev/null
   URL=$(BuildEeDomusUrl $EEDOMUS_IP $MACRO_ID $EEDOMUS_USER $EEDOMUS_PASS 1 $PORTAL )
   ERR=$(GetUrl $URL)

   if [ "$ERR" -eq "0" ]; then
     if [ -e "/tmp/curlout" ]; then
       VAL=`cat /tmp/curlout | sed 's/"/\\\\"/g'`
     else
       VAL="No output received from command"
     fi
     DATA='{"return":"0","msg":"'$VAL'"}'
   else
     DATA='{"return":"1","msg":"'$(GetCurlError $ERR)'"}'
   fi

SendResponse "$DATA"

