#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

KillProcess
ReadUrlParam

TAG_ID=${URLParam[tag]}
ZIBASE_IP=${URLParam[ip]}
CMD_ID=${URLParam[cmd]}

CheckMandatoryParameter "$TAG_ID" tag
CheckMandatoryParameter "$ZIBASE_IP" ip
CheckMandatoryParameter "$CMD_ID" cmd

if [ ! -e "$CNF_DATADIR/Rfid/$TAG_ID.rfid" ]; then
   DATA='{"return":"1","msg":"Tag ID not found."}'
   SendResponse "$DATA"
   exit 0
fi

# Clear existing information
rm -f $CNF_DATADIR/Rfid/$TAG_ID.cmd >>/dev/null 2>>/dev/null
rm -f $CNF_DATADIR/Rfid/$TAG_ID.var>>/dev/null 2>>/dev/null
rm -f $CNF_DATADIR/Rfid/$TAG_ID.action >>/dev/null 2>>/dev/null
rm -f $CNF_DATADIR/Rfid/$TAG_ID.name >>/dev/null 2>>/dev/null

if [ "$TAG_ID" != "" ]; then
  echo $TYPE_ZIBASE > $CNF_DATADIR/Rfid/$TAG_ID.cmd          
   
  if [ "$CMD_ID" != "" ]; then 
    echo $CMD_ID > $CNF_DATADIR/Rfid/$TAG_ID.var
  fi

   if [ "$NAME" != "" ]; then                          
     echo $( echo "$NAME" | UrlDecode) > $CNF_DATADIR/Rfid/$TAG_ID.name
   fi 
   URL=$(BuildZibaseUrl $ZIBASE_IP $CMD_ID)
   echo $URL | base64 > $CNF_DATADIR/Rfid/$TAG_ID.action
fi

DATA='{"return":"0"}'
SendResponse "$DATA"


