#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url_ext.inc
source /www/cgi-bin/utils.inc

cgi_getvars BOTH ALL

CheckMandatoryParameter "$tag" tag
CheckMandatoryParameter "$url" url

TAG_ID=$tag
URL=`echo $url | base64 -d`
URL="curl -L -k -s -o /tmp/curlout \""$URL"\""

if [ ! -e "$CNF_DATADIR/Rfid/$TAG_ID.rfid" ]; then
   DATA='{"return":"1","msg":"Tag ID not found."}'
   SendResponse "$DATA"
   exit 0
fi

# Clear existing information
rm -f $CNF_DATADIR/Rfid/$TAG_ID.cmd >>/dev/null 2>>/dev/null
rm -f $CNF_DATADIR/Rfid/$TAG_ID.var>>/dev/null 2>>/dev/null
rm -f $CNF_DATADIR/Rfid/$TAG_ID.action >>/dev/null 2>>/dev/null
rm -f $CNF_DATADIR/Rfid/$TAG_ID.name >>/dev/null 2>>/dev/null

if [ "$TAG_ID" != "" ]; then
  echo $TYPE_KAROTZ > $CNF_DATADIR/Rfid/$TAG_ID.cmd          
  echo "-1" > $CNF_DATADIR/Rfid/$TAG_ID.var
  echo $URL | base64  > $CNF_DATADIR/Rfid/$TAG_ID.action
fi

DATA='{"return":"0"}'
SendResponse "$DATA"


