#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/ears.inc
source /www/cgi-bin/webcam.inc

KillProcess

# Check Rfid Dir
if [ ! -d "$CNF_DATADIR/Rfid" ]; then
  DATA='{"return":"1","msg":"Rfid directory missing"}'
  SendResponse "$DATA"
  exit
fi

# Check USB Key Availability
mountpoint -q /mnt/usbkey  >> /dev/null 2>> /dev/null
if [  ! $? -eq 0  ]; then
  DATA='{"return":"1","msg":"No USB Key available for Backup"}'
  SendResponse "$DATA"
  exit
fi

find  $CNF_DATADIR/Rfid -name "*.rfid" > $CNF_DATADIR/Tmp/tmplst
NB=$(cat $CNF_DATADIR/Tmp/tmplst | wc -l)
rm -f $CNF_DATADIR/Tmp/tmplst >> /dev/null 2>> /dev/null
if [ $NB -gt 0  ]; then
  BNAME="rfid.backup"
  cd $CNF_DATADIR/Rfid 
  tar cvf $CNF_DATADIR/$BNAME.tar * >> /dev/null 2>> /dev/null
  gzip /$CNF_DATADIR/$BNAME.tar >> /dev/null 2>> /dev/null
  DATA='{"return":"0","file":"'$CNF_DATADIR/$BNAME.tar.gz'"}'
else
  DATA='{"return":"1","msg":"No Rfid informations to backup."}'
  SendResponse "$DATA"
  exit
fi

SendResponse "$DATA"




