#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

#KillProcess
ReadUrlParam

TAG_ID=${URLParam[tag]}
NAME=${URLParam[name]}
COLOR=${URLParam[color]}

CheckMandatoryParameter "$TAG_ID" tag
#CheckMandatoryParameter "$NAME" name
#CheckMandatoryParameter "$COLOR" color

if [ ! -e "$CNF_DATADIR/Rfid/$TAG_ID.rfid" ]; then
   DATA='{"return":"1","msg":"Tag ID not found."}'
   SendResponse "$DATA"
   exit 0
fi


# Update informations
echo $RFID_COLOR > $CNF_DATADIR/Rfid/${RFID_ID}.color

if [ "$NAME" != "" ]; then                          
     echo $( echo "$NAME" | UrlDecode) > $CNF_DATADIR/Rfid/$TAG_ID.name
else
     rm -f $CNF_DATADIR/Rfid/$TAG_ID.name >> /dev/null 2>> /dev/null
fi 

if [ "$COLOR" != "" ]; then
     echo "$COLOR" > $CNF_DATADIR/Rfid/$TAG_ID.color
else
    echo "31" > $CNF_DATADIR/Rfid/$TAG_ID.color
fi
   

DATA='{"return":"0"}'
SendResponse "$DATA"


