#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

NTP_RET=`ntpd -n -q -p pool.ntp.org 2>> /var/log/messages`

DATA='{"return":"0"}'
SendResponse "$DATA"
