#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/ears.inc
source /www/cgi-bin/webcam.inc

KillProcess LEDS

ReadUrlParam
TDIR=$CNF_DATADIR"/Snapshots/"

SILENT=${URLParam[silent]}
            
FN="snapshot"_`date +'%Y_%m_%d_%H_%M_%S'`
TakeSnapshot

if [ ! -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
  LedsRestore
  if [ "$SILENT" == "" ]; then
    PlaySound /usr/karotz/res/sounds/webcam.mp3
  fi
fi

if [ ! -e "/tmp/picture.jpg" ]; then
    exit 0
fi

echo "Server: OpenKarotz WebServer 1.0"
echo "Connection: close"
echo "Accept-Ranges: bytes"
echo "Content-type: image/jpeg"
echo "Access-Control-Allow-Origin: *"
echo ""
cat /tmp/picture.jpg

