#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory  "$CNF_DATADIR/Sounds"

NB=$(ls -1 -A $CNF_DATADIR/Sounds | grep '.mp3' | grep -v '/$' | wc -l)
TG=''
HEAD='{ "sounds": [ '
if [ $NB -gt 0  ]; then
   for f in $( ls $CNF_DATADIR/Sounds/*.mp3  )
      do
           FNAME=$(echo $f  | cut -d '/' -f 5)
                TG=$TG'{ "id":"'${FNAME%%.*}'"},'
                    done
                    fi
                    TG=${TG%?}
                    TAIL='], "return":"0" }'
                    rm -f $CNF_DATADIR/Tmp/tmplst >> /dev/null 2>> /dev/null
                    DATA=$HEAD$TG$TAIL
                    
                    SendResponse "$DATA"
