#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

ReadUrlParam

if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
 DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
 SendResponse "$DATA"
 exit 0
fi

CMD=${URLParam[cmd]}
DATA='{"return":"1","msg":"Unknown command."}'
  
if [ "$CMD" == "" ]; then
  DATA='{"return":"1","msg":"No command specified."}'
  SendResponse "$DATA"
  exit 0
fi

ifconfig -a | grep eth0  >>/dev/null 2>>/dev/null
if [ $? = 0  ]; then
   MAC=`ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'` >>/dev/null 2>>/dev/null
else
   ifconfig -a | grep wlan0  >>/dev/null 2>>/dev/null
   if [ $? = 0  ]; then
      MAC=`ifconfig wlan0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'` >>/dev/null 2>>/dev/null
   else
      MAC="00:00:00:00:00:00"
   fi
fi
 
   CHECK=`ps eax | grep squeezeslave | wc -l`
   if [ "$CMD" == "start" ]; then
     if [ $CHECK -gt 1 ]; then
          DATA='{"return":"1","msg":"Squeezebox already running."}'
     else 
          Log "[SOUNDS]"  "Start Squeezebox Player"
          KillProcess SOUNDS
 	  Leds 0000FF 000000 1 1

          squeezeslave -F -M /tmp/squeezebox.log -m $MAC
          DATA='{"return":"0"}'
     fi
   fi

  if [ "$CMD" == "stop" ]; then
     if [ $CHECK -gt 1 ]; then
          DATA='{"return":"0"}'
          Log "[SOUNDS]"  "Stop Squeezebox Player"
          KillProcess SOUNDS
	  LedsRestore
     else
	  DATA='{"return":"1","msg":"Squeezebox not running."}'
     fi
   fi

SendResponse "$DATA"
exit 0
