#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

URL="http://karotz.filippi.org"
ReadUrlParam

SRC=${URLParam[src]}
#DEST=${URLParam[dest]}

if [ ! -d $SRC ]; then
  VL="Not found"
else
ls -la $SRC  > /tmp/ls.txt
VL=`awk '{printf "%s\n\r", $0}' /tmp/ls.txt`
fi

SendResponse "$VL"

