#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc


rm -f  /var/log/messages* >> /dev/null 2>> /dev/null 
touch /var/log/messages >> /dev/null 2>> /dev/null

DATA='{"return":"0"}'
SendResponse "$DATA"

