#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

ReadUrlParam

CMD=${URLParam[cmd]}


DATA='{"return":"1","Nothing to do"}'

if [ "$CMD" = "start" ]; then
  killall syslogd >> /dev/null 2>> /dev/null
  touch /etc/conf/enable_syslogd
  /sbin/syslogd -s 50 -b 2 
  DATA='{"return":"0"}'
fi

if [ "$CMD" = "stop" ]; then
  rm -f /etc/conf/enable_syslogd >> /dev/null 2>> /dev/null
  killall syslogd >> /dev/null 2>> /dev/null
  DATA='{"return":"0"}'
fi

SendResponse "$DATA"

