#!/usr/bin/python
# -*- coding:Utf-8 -*
print("Content-Type: multipart/x-mixed-replace; boundary=--ffserver\n")

import cgi
import cgitb; cgitb.enable(display=1, logdir='/tmp')
import subprocess

if __name__ == '__main__':
	command = 'ffmpeg -f rawvideo -pix_fmt rgb565 -r 1 -s 640x480 -i /dev/camera -f mpjpeg -vcodec mjpeg -qscale 1 -r 1 pipe:1 2>/dev/null'
	p = subprocess.Popen(command, stdout=subprocess.PIPE, bufsize=-1, shell=True)
	while(p.poll() is None):
        	stdoutdata = p.stdout.read(400200)
                print(stdoutdata)
                                                        
