#
# Global paramters
#
# Max Files in cache
CNF_MAX_CACHE_SIZE=100

# File Location
TDIR="/usr/www/"
CNF_DATADIR="/usr/openkarotz/"

# Disable Ears
CNF_EARS_DISABLED=0

# RFID Action active even when Karotz is Sleeping
CNF_RFID_ALWAYS_ACTIVE=1

# Breeze Color
CNF_BREEZE_COLOR=00FF00

# Karotz Gender
# M : Male
# F : Female
CNF_GENDER=F

# Base URL
CNF_BASE_URL="http://karotz.filippi.org/2.0"
SOURCES_CNF="$CURRDIR/sources/openkarotz"
SOURCES_TDIR="$CURRDIR/sources/www"

