#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/url.inc

ReadUrlParam

L=${URLParam[url]}
#L=$1

R=$(curl -w %{http_code} -s -L -k -o /tmp/curlout "$CNF_BASE_URL")
if [ "$R" -eq "200" ]; then
  DT=`cat /tmp/curlout`
  rm -f /tmp/curlout
else
 DT='{"return":"1","msg":"Error reading file"}'
fi

SendResponse  "$DT"
