#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

KillProcess
ReadUrlParam

APP=${URLParam[app]}

CheckMandatoryParameter "$APP" app
CheckMandatoryDirectory  "$CNF_DATADIR/Apps"
CheckMandatoryDirectory  "$CNF_DATADIR/Apps/Clock"
CheckMandatoryDirectory  "$CNF_DATADIR/Apps/Clock/Data"

if [ -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
   DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
      SendResponse "$DATA"
         exit 0
         fi


SendResponse "$AL"
