#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc

if [ ! -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
   ping 8.8.8.8 -c 3 -q  >>/dev/null 2>>/dev/null
   if [ ! $? -eq 0 ]; then
     Log  "Lost Network connexion" 1
     Leds FF0000 0000FF 1 1 100 
     Log "[SYSTEM]"  "Check Network Health - Reboot " 1
     /sbin/reboot     
  else
     LedsRestore
     Log "[SYSTEM]"  "Check Network Health - OK"
  fi
fi
