#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

CheckMandatoryDirectory "/www/cgi-bin"

chmod 777 /usr/www >> /dev/null 2>> /dev/null 
chmod -R 777 /usr/www/cgi-bin >> /dev/null 2>> /dev/null


DATA='{"return":"0"}'
SendResponse "$DATA"

