#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/leds.inc

KillProcess LEDS
killall crond >>/dev/null 2>>/dev/null
ReadUrlParam

Leds FFA500

FLASH_VERSION=${URLParam[version]}
if [ "$FLASH_VERSION" == "" ]; then
  FLASH_VERSION=$1
fi

CheckMandatoryParameter "$FLASH_VERSION" version

# >>/dev/null 2>>/dev/null
Log "[UPDATE][FLASH]"  "Start Update to Firmware $FLASH_VERSION"

rm -f /tmp/rootfs.openkarotz.img.gz >>/dev/null 2>>/dev/null
rm -f /tmp/rootfs.openkarotz.img.gz.md5 >>/dev/null 2>>/dev/null

Leds FFA533 000000 1

Log "[UPDATE][FLASH]"  "Downloading utility file(s)"
wget $CNF_ROOT_URL/Firmware/sounds/download.mp3 -q -O /tmp/download.mp3 >>/dev/null 2>>/dev/null
PlaySound /tmp/download.mp3

wget $CNF_ROOT_URL/Firmware/sounds/install.mp3 -q -O /tmp/install.mp3 >>/dev/null 2>>/dev/null
wget $CNF_ROOT_URL/Firmware/sounds/error.mp3 -q -O /tmp/error.mp3 >>/dev/null 2>>/dev/null
wget $CNF_ROOT_URL/Firmware/sounds/ok.mp3 -q -O /tmp/ok.mp3 >>/dev/null 2>>/dev/null

wget $CNF_ROOT_URL/Firmware/$FLASH_VERSION/rootfs.openkarotz.img.gz -q -O /tmp/rootfs.openkarotz.img.gz >>/dev/null 2>>/dev/null
wget $CNF_ROOT_URL/Firmware/$FLASH_VERSION/rootfs.openkarotz.img.gz.md5 -q -O /tmp/rootfs.openkarotz.img.gz.md5 >>/dev/null 2>>/dev/null

PlaySound /tmp/install.mp3
Leds FFA500 000000 1

if [ ! -e "/tmp/rootfs.openkarotz.img.gz" ]; then
 Log "[UPDATE][FLASH]"  "Unable to find rootfs file" 1
 PlaySound /tmp/error.mp3
 DATA='{"return":"1","msg":"Unable to find rootfs file"}'
 SendResponse "$DATA"
 exit 0
fi

if [ ! -e "/tmp/rootfs.openkarotz.img.gz.md5" ]; then
  Log "[UPDATE][FLASH]"  "Unable to find rootfs signature file" 1
  PlaySound /tmp/error.mp3
  DATA='{"return":"1","msg":"Unable to find rootfs file"}'
  SendResponse "$DATA"
  exit 0
fi

cd /tmp
md5sum -c -s /tmp/rootfs.openkarotz.img.gz.md5
if [ $? -eq 0 ]; then
  Log "[UPDATE][FLASH]"  "rootfs Integrity OK"
else
 Log "[UPDATE][FLASH]"  "rootfs Integrity verification failed" 1 
 PlaySound /tmp/error.mp3
 DATA='{"return":"1","msg":"rootfs Integrity verification failed"}'
 SendResponse "$DATA"
 exit 0
fi

Log "[UPDATE][FLASH]"  "Erasing flash"
/sbin/flash_eraseall -q /dev/mtd2 

Log "[UPDATE][FLASH]"  "Updating flash"
/sbin/nandwrite -q -pm /dev/mtd2 /tmp/rootfs.openkarotz.img.gz

rm -f /tmp/rootfs.openkarotz.img.gz >>/dev/null 2>>/dev/null
rm -f /tmp/rootfs.openkarotz.img.gz.md5 >>/dev/null 2>>/dev/null

Log "[UPDATE][FLASH]"  "Flash succesfully updated to version $FLASH_VERSION"
PlaySound /tmp/ok.mp3

Leds 00FF00 000000 1

DATA='{"return":"0"}'
SendResponse "$DATA"
reboot -d 15 >>/dev/null 2>>/dev/null &







