#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

URL="http://karotz.filippi.org"
ReadUrlParam

SRC=${URLParam[src]}
DEST=${URLParam[dest]}

wget $URL/$SRC -O $CNF_DATADIR/$DEST

VL='{ "return":"0" }'

SendResponse "$VL"

