#!/bin/bash

source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/setup.inc

TDIR="/usr/www"
UDIR="$CNF_DATADIR"
URL="$CNF_BASE_URL"

ReadUrlParam

ID=${URLParam[id]}
FILE=${URLParam[file]}

CheckMandatoryParameter "$ID" id
CheckMandatoryParameter "$FILE" file

# Get update file from server
wget $URL/update/$ID/$FILE -O /tmp/$FILE -q >> /dev/null 2>> /dev/null

# Check file
if [ ! -e "/tmp/$FILE" ]; then
  Log "[Update]" "Unable to get file : $URL/update/$ID/$FILE" 1
  DATA='{"return":"1","msg":"Unable to read file"}'
  SendResponse "$DATA"
  exit 0
else
  Log "[Update]" "Reading file : $URL/update/$ID/$FILE"
  chmod 777 /tmp/$FILE >> /dev/null 2>> /dev/null
fi

# Launch update file
Log "[Update]" "Starting update"
bash /tmp/$FILE >> /dev/null 2>> /dev/null

# Remove update file
rm -f /tmp/$FILE >> /dev/null 2>> /dev/null


DATA='{"return":"0"}'
SendResponse "$DATA"
