#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/ears.inc
source /www/cgi-bin/webcam.inc

KillProcess

# Check Rfid Dir
if [ ! -d "$CNF_DATADIR/Rfid" ]; then
  DATA='{"return":"1","msg":"Rfid directory missing"}'
  SendResponse "$DATA"
  exit
fi

# Check Backup File Availability
if [ ! -e "$CNF_DATADIR/rfid.backup.tar.gz" ]; then
  DATA='{"return":"1","msg":"No backup to restore"}'
  SendResponse "$DATA"
  exit
fi

cd $CNF_DATADIR/Rfid 
mv $CNF_DATADIR/rfid.backup.tar.gz $CNF_DATADIR/Rfid 
tar zxvf $CNF_DATADIR/Rfid/rfid.backup.tar.gz    
rm -f $CNF_DATADIR/Rfid/rfid.backup.tar.gz   

DATA='{"return":"0"}'

SendResponse "$DATA"




