#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

if [ ! -d $CNF_DATADIR"/Snapshots" ]; then
  DATA='{"return":"1","msg":"Snapshots directory missing"}'
  SendResponse "$DATA"
  exit
fi       
 

NB=$(ls -1 -A $CNF_DATADIR/Snapshots | grep ".jpg" | wc -l)
TG=''
HEAD='{ "snapshots": ['
if [ $NB -gt 0  ]; then
   for f in $( ls $CNF_DATADIR/Snapshots/*.jpg  )
   do
     TG=$TG'{ "id":"'$(echo $f  | cut -d '/' -f 5)'"},'
    done
    TG=${TG%?}
fi
TAIL='], "return":"0" }'
DATA=$HEAD$TG$TAIL

SendResponse "$DATA"
