#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc

URL="http://karotz.filippi.org"
ReadUrlParam

#SRC=${URLParam[src]}
#DEST=${URLParam[dest]}

ps eax > /tmp/ps.txt
VL=`awk '{printf "%s\n\r", $0}' /tmp/ps.txt`
rm -f /tmp/ps.txt

SendResponse "$VL"

