#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc


if [ ! -e "$CNF_DATADIR/Run/vera.ip" ]; then
  VERA_IP=""
else
  VERA_IP=$(cat $CNF_DATADIR/Run/vera.ip)
fi


L0='{'
L1='"ip":"'$VERA_IP'"'
L2=',"return":"0"'
L3='}'
DATA=$L0$L1$L2$L3

SendResponse "$DATA"
