#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc


if [ ! -e "$CNF_DATADIR/Run/zibase.ip" ]; then
  Z_IP=""
else
  Z_IP=$(cat $CNF_DATADIR/Run/zibase.ip)
fi


L0='{'
L1='"ip":"'$Z_IP'"'
L2=',"return":"0"'
L3='}'
DATA=$L0$L1$L2$L3

SendResponse "$DATA"
