#!/bin/bash

source /usr/www/cgi-bin/setup.inc
source /usr/www/cgi-bin/url.inc
source /usr/www/cgi-bin/utils.inc
source /usr/www/cgi-bin/ears.inc

Log "[MOODS]" "Moods Called"

KillProcess LEDS
KillProcess SOUNDS
ReadUrlParam

CheckMandatoryDirectory  "$CNF_DATADIR/Moods"
CheckMandatoryDirectory  "$CNF_DATADIR/Moods/fr"

MOODS_ID=${URLParam[id]}
LANG=${URLParam[lang]}
if [ "$LANG" = "" ]; then
   LANG="fr"
fi

if [ "$MOODS_ID" = "" ]; then
    r=$RANDOM
    MOODS=$(( r %= 305 )) 
else
    MOODS=$MOODS_ID    
fi    

if [ ! -e "$CNF_DATADIR/Moods/fr/${MOODS}.mp3" ]; then
  DATA='{"return":"1","msg":"Moods not found"}'
  Log "[MOODS]"  "Moods not found"
  SendResponse "$DATA"  
  exit 0
fi


if [ ! -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
   EarsReset
   if [ ! -e "$CNF_DATADIR/Moods/fr/${MOODS}.mp3" ]; then
      DATA='{"return":"1","msg":"File not found."}'
   else
      PlaySound $CNF_DATADIR/Moods/fr/${MOODS}.mp3 1
      DATA='{"moods":"'$MOODS'","return":"0"}'
      Log "[MOODS]"  "Moods $MOODS played"
   fi
else
   DATA='{"return":"1","msg":"Unable to perform action, rabbit is sleeping."}'
   Log "[MOODS]"  "Rabbit if sleeping."
fi

SendResponse "$DATA"
